spring.application.name=user-service

# Always check your logs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG



# Always use ANSI color codes in logs
spring.output.ansi.enabled=ALWAYS