spring:
  application:
    name: user-service
  output:
    ansi:
      enabled: always

server:
  port: 8081

# Always check your logs
logging:
  level:
    org:
    springframework:
      security: DEBUG
      web: DEBUG
